# Generated by Django 5.1.5 on 2025-02-04 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccess',
            old_name='data',
            new_name='data_acesso',
        ),
    ]
